disabled_rules:
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - vertical_parameter_alignment
  - closure_parameter_position
  - todo
  - superfluous_disable_command
  - trailing_whitespace
  - unused_closure_parameter

opt_in_rules:
  - static_operator
  - empty_count
  - explicit_init
  - closure_spacing
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - fatal_error_message
  - unneeded_parentheses_in_closure_argument
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation
  - joined_default_parameter
  - contains_over_first_not_nil
  - override_in_extension
  - private_action
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - sorted_first_last

line_length: 160

type_body_length:
  - 300 # warning
  - 300 # error (должно быть 300)

file_length:
  warning: 400 # warning
  error: 400 # error (должно быть 400)
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    error: 2
  max_length:
    error: 50
  excluded:
    - id

nesting:
  type_level: 3

cyclomatic_complexity:
  ignores_case_statements: true

excluded:
  - Carthage
  - Pods
